### PR TITLE
Add TermsHistogram method for relative search

### PR DESCRIPTION
**Pull request by scadox**

### CODE REVIEW

**Comment by soullivaneuh** [comment]
Do you have a link of the related documentation? :thinking:

**Comment by scadox** [comment]
In this image you can see the API call available from the documentation

image

**Comment by soullivaneuh** [comment]
Oh right, that's true. The documentation is available on the tools only. That's quite a shame BTW. :upside_down_face: 

Looks good to me, thanks for your work! :+1:

**Comment by soullivaneuh** [comment]
Here is your release: https://github.com/nexylan/graylog-sdk/releases/tag/v0.7.0

**Comment by scadox** [comment]
Yeahh thank you for fast job @soullivaneuh . Have a good day

Cordialement,
Matthew Lafrance

**Pull request merged**
